document.getElementById("myBtn").onclick = function genNow() {
	let str = Math.floor(Math.random() * 100) + 1;
	let dex = Math.floor(Math.random() * 100) + 1;
	let con = Math.floor(Math.random() * 100) + 1;

	// 	This block controls the first part of the generator //
	if (str <= 5) {
		str = "Order";
	} else if (str <= 10) {
		str = "Clan";
	} else if (str <= 15) {
		str = "Fellowship";
	} else if (str <= 20) {
		str = "House";
	} else if (str <= 25) {
		str = "Guild";
	} else if (str <= 30) {
		str = "Army";
	} else if (str <= 35) {
		str = "Band";
	} else if (str <= 40) {
		str = "Coven";
	} else if (str <= 45) {
		str = "Tribe";
	} else if (str <= 50) {
		str = "Gathering";
	} else if (str <= 55) {
		str = "Union";
	} else if (str <= 60) {
		str = "Society";
	} else if (str <= 65) {
		str = "Alliance";
	} else if (str <= 70) {
		str = "Assosiation";
	} else if (str <= 75) {
		str = "Circle";
	} else if (str <= 80) {
		str = "Syndicate";
	} else if (str <= 85) {
		str = "Council";
	} else if (str <= 90) {
		str = "League";
	} else if (str <= 95) {
		str = "Outfit";
	} else if (str <= 100) {
		str = "Scorned";
	} else {
		str = "Error Please Try Again";
	}

	// This block Controls the second part of the Generator //
	if (dex <= 5) {
		dex = "Running";
	} else if (dex <= 10) {
		dex = "Lauging";
	} else if (dex <= 15) {
		dex = "Flaming";
	} else if (dex <= 20) {
		dex = "Raging";
	} else if (dex <= 25) {
		dex = "Frosted";
	} else if (dex <= 30) {
		dex = "Dancing";
	} else if (dex <= 35) {
		dex = "Fighting";
	} else if (dex <= 40) {
		dex = "Rising";
	} else if (dex <= 45) {
		dex = "Shattering";
	} else if (dex <= 50) {
		dex = "Sleeping";
	} else if (dex <= 55) {
		dex = "Fleeting";
	} else if (dex <= 60) {
		dex = "Silent";
	} else if (dex <= 65) {
		dex = "Creeping";
	} else if (dex <= 65) {
		dex = "Stalking";
	} else if (dex <= 70) {
		dex = "Grumpy";
	} else if (dex <= 75) {
		dex = "Forsaken";
	} else if (dex <= 80) {
		dex = "Grieving";
	} else if (dex <= 85) {
		dex = "Golden";
	} else if (dex <= 90) {
		dex = "Darkened";
	} else if (dex <= 95) {
		dex = "Wandering";
	} else if (dex <= 100) {
		dex = "Angry";
	} else {
		dex = "Error Please Try Again";
	}

	if (con <= 5) {
		con = "Wolf";
	} else if (con <= 10) {
		con = "Boar";
	} else if (con <= 15) {
		con = "Bear";
	} else if (con <= 20) {
		con = "Scorpion";
	} else if (con <= 25) {
		con = "Spider";
	} else if (con <= 30) {
		con = "Raven";
	} else if (con <= 35) {
		con = "Dove";
	} else if (con <= 40) {
		con = "Falcon";
	} else if (con <= 45) {
		con = "Lion";
	} else if (con <= 50) {
		con = "Panther";
	} else if (con <= 55) {
		con = "Sun";
	} else if (con <= 60) {
		con = "Moon";
	} else if (con <= 65) {
		con = "Star";
	} else if (con <= 70) {
		con = "Shadows";
	} else if (con <= 75) {
		con = "Fox";
	} else if (con <= 80) {
		con = "Warriors";
	} else if (con <= 85) {
		con = "Mist";
	} else if (con <= 90) {
		con = "Eagle";
	} else if (con <= 95) {
		con = "Dragon";
	} else if (con <= 100) {
		con = "Jackal";
	} else {
		con = "Error Please Try Again";
	}

	document.getElementById("text").innerHTML = str + " of the " + dex + " " + con;
};